FROM node:carbon-alpine as builder

WORKDIR /app

COPY ./package.json /
COPY ./package-lock.json /

RUN npm i

COPY . .

CMD ["npm","run","build"]

FROM nginx:alpine

COPY ./.nginx /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html