FROM node:carbon-alpine as builder

WORKDIR /app

COPY . .
RUN rm -f /app/node_modules

RUN npm i

RUN npm run build

RUN cp -ar /app/dist /
RUN cp -ar /app/.nginx /

RUN rm -rf /app

FROM nginx:alpine

COPY --from=builder /.nginx /etc/nginx/conf.d/default.conf
COPY --from=builder /dist /usr/share/nginx/html