sudo: required
services:
  - docker

env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
#  magic don't touch
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d

  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project test-docker-214117
  - gcloud config set compute/zone southamerica-east1-a
  - gcloud container clusters get-credentials microweb

  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker build -t test -f ./client/docker/Dockerfile.test ./client

script:
  - docker run test npm run lint

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
