sudo: required
services:
  - docker


before_install:
  - docker build -t test -f ./client/Dockerfile.test ./client

script:
  - docker run test npm run lint

after_success:
  - docker build -t blademaster996/micro-web-client -f ./client/Dockerfile.production ./client
  - docker build -t blademaster996/micro-web-server -f ./server/Dockerfile.production ./server
  - docker build -t blademaster996/micro-web-worker -f ./worker/Dockerfile.production ./worker
  - docker build -t blademaster996/micro-web-nginx                                    ./nginx

  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

  - docker push blademaster996/micro-web-client
  - docker push blademaster996/micro-web-server
  - docker push blademaster996/micro-web-nginx
  - docker push blademaster996/micro-web-worker