version: '3'
services:

  nginx:
    restart: always
    build: nginx
    ports:
      - 4200:80

  postgres:
    env_file:
      - ./.env
    image: postgres:alpine

  redis:
    env_file:
      - ./.env
    image: redis:alpine

  client:
    build:
      context: client
      dockerfile: Dockerfile.${NODE_ENV}
    volumes:
      - ./client:/app

  server:
    env_file:
      - ./.env
    build:
      context: server
      dockerfile: Dockerfile.${NODE_ENV}
    volumes:
      - ./server:/app
    links:
      - postgres
      - redis

  worker:
    env_file:
      - ./.env
    build:
      context: worker
      dockerfile: Dockerfile.${NODE_ENV}
    links:
      - redis
    volumes:
      - ./worker:/app