version: '3'
services:

  nginx:
    restart: always
    build: nginx
    ports:
      - 4200:80

  client:
    build:
      context: client
      dockerfile: docker/Dockerfile.${NODE_ENV}
    volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
      - ./client/docker/command.${NODE_ENV}.sh:/command.sh

  server:
    env_file:
      - ./.env
    build:
      context: server
      dockerfile: Dockerfile.${NODE_ENV}
    volumes:
      - ./server:/app
      - /app/node_modules
