version: '3'
services:

  nginx:
    restart: always
    build: nginx
    ports:
      - 4200:80

  postgres:
    env_file:
      - ./.env
    image: postgres:alpine

  redis:
    env_file:
      - ./.env
    image: redis:alpine

  client:
    build:
      context: client
      dockerfile: docker/Dockerfile.${NODE_ENV}
    command: /command.${NODE_ENV}.sh
    volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
      - ./client/docker/command.sh:/command.sh

  server:
    env_file:
      - ./.env
    build:
      context: server
      dockerfile: Dockerfile.${NODE_ENV}
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - postgres
      - redis

  worker:
    env_file:
      - ./.env
    build:
      context: worker
      dockerfile: Dockerfile.${NODE_ENV}
    links:
      - redis
    volumes:
      - ./worker:/app
      - /app/node_modules
