FROM golang:alpine

#RUN wget -q -O /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x /usr/local/bin/dep

#RUN mkdir -p /go/src/github.com/duongvanha/micro-web

WORKDIR /go/src/github.com/duongvanha/micro-web/worker

COPY . .

#RUN dep ensure -vendor-only

CMD ["go","run","main.go"]
